### ISSUE TITLE
flatpak manifest

### ISSUE THREAD

**Issue by gthreepw00d** [enz/pentobi#10]
```yaml
app-id: io.sourceforge.pentobi
runtime: org.kde.Platform
runtime-version: '5.15'
sdk: org.kde.Sdk
command: /app/bin/pentobi
cleanup:
  - '/lib/debug'
finish-args:
  - --socket=x11
  - --socket=wayland
  - --share=ipc
  - --device=dri
modules:
  - name: pentobi
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DDOCBOOKXSL_DIR=/usr/share/xml/docbook/xml/xsl-stylesheets
#no qt5-qtwebview in sdk
      - -DPENTOBI_OPEN_HELP_EXTERNALLY=ON
    sources:
      - type: git
        url: https://github.com/enz/pentobi.git
        tag: v18.3
```
